# Generated by Django 4.2.1 on 2023-06-14 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Technicien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="media/profile", verbose_name="profile"
                    ),
                ),
                ("nom", models.CharField(max_length=50, verbose_name="nom")),
                ("prenom", models.CharField(max_length=50, verbose_name="prenom")),
                ("tel", models.CharField(max_length=20, verbose_name="telephone")),
                ("email", models.EmailField(max_length=254)),
                (
                    "matricule",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="matricune"
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_upd", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technicien",
                "verbose_name_plural": "Techniciens",
                "db_table": "",
                "managed": True,
            },
        ),
    ]
