# Generated by Django 4.2.1 on 2023-07-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='technicien',
            table=None,
        ),
    ]
