# Generated by Django 4.2.1 on 2023-06-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='photo',
            field=models.ImageField(default=1, height_field=400, upload_to='profile', verbose_name='profile', width_field=400),
            preserve_default=False,
        ),
    ]
