# Generated by Django 4.2.1 on 2023-06-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0003_alter_technicien_matricule_alter_technicien_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicien',
            name='photo',
            field=models.ImageField(upload_to='profile', verbose_name='profile'),
        ),
    ]
