# Generated by Django 4.2.1 on 2023-08-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0004_alter_technicien_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressource.technicien', verbose_name='echnicien')),
            ],
        ),
        migrations.DeleteModel(
            name='Ajax',
        ),
    ]
