# Generated by Django 4.2.1 on 2023-06-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0004_alter_technicien_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicien',
            options={'managed': True, 'verbose_name': 'Technicien', 'verbose_name_plural': 'Techniciens'},
        ),
        migrations.AlterModelTable(
            name='technicien',
            table='',
        ),
    ]
