# Generated by Django 4.2.1 on 2023-06-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0005_alter_technicien_options_alter_technicien_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicien',
            name='photo',
            field=models.ImageField(upload_to='media/profile', verbose_name='profile'),
        ),
    ]
