# Generated by Django 4.2.1 on 2023-08-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0005_stateday_delete_ajax'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='efficacite',
            field=models.FloatField(default=0.0, verbose_name='Efficacité'),
        ),
        migrations.AddField(
            model_name='technicien',
            name='vitesse_execution',
            field=models.FloatField(default=0.0, verbose_name="Vitesse d'exécution"),
        ),
    ]
