# Generated by Django 4.2.1 on 2023-10-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0006_technicien_efficacite_technicien_vitesse_execution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicien',
            name='photo',
            field=models.ImageField(upload_to='profile', verbose_name='profile'),
        ),
    ]
