# Generated by Django 4.2.1 on 2023-06-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("ressource", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("En atente", "En atente"),
                            ("En cours", "En cours"),
                            ("En arret", "En arret"),
                            ("En facturation", "En facturation"),
                        ],
                        max_length=20,
                        verbose_name="nom de l'etat",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=50, verbose_name="des criprion de l'etat"
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        default="RAS", max_length=50, verbose_name="motif de l'etat"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, verbose_name="name")),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("Bas", "Bas"),
                            ("Moyen", "Moyen"),
                            ("Elever", "Elever"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(default="description", max_length=500),
                ),
                (
                    "n_OS",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="numero d OS"
                    ),
                ),
                ("ok", models.BooleanField(default=False)),
                (
                    "observation",
                    models.CharField(default="observation", max_length=100),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de debut"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="date de fin"),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        max_length=20,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.agence",
                    ),
                ),
                (
                    "appelant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.appelant",
                        verbose_name=" celui qui appel ",
                    ),
                ),
                (
                    "etat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.etat",
                        verbose_name="etat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tache",
                "verbose_name_plural": "Taches",
                "ordering": ["createdAt"],
            },
        ),
        migrations.CreateModel(
            name="TechnicienTache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, verbose_name="equipe")),
                (
                    "tache",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.tache"
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ressource.technicien",
                        verbose_name="techniciens",
                    ),
                ),
            ],
            options={
                "unique_together": {("technicien", "tache", "nom")},
            },
        ),
        migrations.CreateModel(
            name="TacheTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jour",
                    models.CharField(
                        choices=[
                            ("lundi", "lundi"),
                            ("mardi", "mardi"),
                            ("mercredi", "mercredi"),
                            ("jeudi", "jeudi"),
                            ("vendredi", "vendredi"),
                            ("samedi", "samedi"),
                        ],
                        max_length=50,
                        verbose_name="jour",
                    ),
                ),
                (
                    "technicientache",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.technicientache",
                    ),
                ),
            ],
        ),
    ]
