# Generated by Django 4.2.1 on 2023-08-31 18:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('ressource', '0006_technicien_efficacite_technicien_vitesse_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donnee_jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EnregistrementJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('taches_creees_count', models.PositiveIntegerField(default=0)),
                ('taches_attribuees_count', models.PositiveIntegerField(default=0)),
                ('taches_effectuees_count', models.PositiveIntegerField(default=0)),
                ('tache_totals', models.PositiveIntegerField(default=0)),
                ('tache_att_total', models.PositiveIntegerField(default=0)),
                ('tache_eff_total', models.PositiveIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapport_text', models.TextField(verbose_name='Rapport')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('technicien_list', models.CharField(max_length=250, null=True, verbose_name='liste des technicien')),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='intitule')),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('En arrêt', 'En arrêt'), ('En facturation', 'En facturation')], default='En attente', max_length=20)),
                ('priorite', models.CharField(choices=[('Bas', 'Bas'), ('Moyen', 'Moyen'), ('Élevé', 'Élevé')], max_length=20)),
                ('description', models.CharField(default='description', max_length=500)),
                ('n_OS', models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'OS")),
                ('ok', models.BooleanField(default=False)),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.activite', verbose_name='Activite')),
                ('appelant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.appelant', verbose_name='Celui qui appelle')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.categorie', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Tache',
                'verbose_name_plural': 'Taches',
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='TechnicienTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=False, verbose_name='tache effectuer')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tache')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ressource.technicien', verbose_name='techniciens')),
            ],
            options={
                'unique_together': {('technicien', 'tache')},
            },
        ),
        migrations.CreateModel(
            name='TacheEffectuee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name="Date d'effectuation")),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('rapport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.rapport', verbose_name='Rapport')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tache', verbose_name='Tâche effectuée')),
            ],
            options={
                'verbose_name': 'Tâche effectuée',
                'verbose_name_plural': 'Tâches effectuées',
            },
        ),
        migrations.AddField(
            model_name='rapport',
            name='technicien_tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.technicientache', verbose_name='Tâche effectuée par le technicien'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('creation', 'Création'), ('attribution', 'Attribution'), ('effectuation', 'Effectuation')], max_length=20, verbose_name="Type d'action")),
                ('date', models.DateField(auto_now_add=True, verbose_name="Date d'action")),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tache')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='TacheAttribuee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribuee', models.DateField(auto_now=True, verbose_name="Date d'attribution")),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tache', verbose_name='Tâche attribuée')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressource.technicien', verbose_name='Technicien')),
            ],
            options={
                'unique_together': {('technicien', 'tache')},
            },
        ),
        migrations.CreateModel(
            name='DonneesTechnicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('taches_attribuees', models.PositiveIntegerField(default=0)),
                ('taches_effectuees', models.PositiveIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressource.technicien')),
            ],
            options={
                'unique_together': {('technicien', 'date')},
            },
        ),
    ]
