# Generated by Django 4.2.1 on 2023-06-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicientache',
            name='ok',
            field=models.BooleanField(default=False),
        ),
    ]
