# Generated by Django 4.2.1 on 2023-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('En arrêt', 'En arrêt'), ('En facturation', 'En facturation'), ('Effectué', 'Effectué')], default='En attente', max_length=20),
        ),
    ]
