# Generated by Django 4.2.1 on 2023-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_tache_options_remove_tache_agence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='technicien',
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='date de debut'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='date de fin'),
        ),
    ]
