# Generated by Django 4.2.1 on 2023-06-09 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('project', '0003_remove_tache_technicien_alter_tache_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='agence',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='clients.agence'),
            preserve_default=False,
        ),
    ]
