# Generated by Django 4.2.1 on 2023-06-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0001_initial'),
        ('project', '0003_alter_technicientache_technicien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicientache',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ressource.technicien', verbose_name='techniciens'),
        ),
    ]
