# Generated by Django 4.2.1 on 2023-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0004_alter_technicien_photo'),
        ('project', '0004_tache_agence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicientache',
            name='tache',
        ),
        migrations.AddField(
            model_name='tache',
            name='technicien',
            field=models.ManyToManyField(blank=True, to='ressource.technicien', verbose_name='technicien'),
        ),
        migrations.RemoveField(
            model_name='technicientache',
            name='technicien',
        ),
        migrations.AddField(
            model_name='technicientache',
            name='technicien',
            field=models.ManyToManyField(blank=True, to='ressource.technicien'),
        ),
    ]
