# Generated by Django 4.2.1 on 2023-07-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0002_alter_technicien_table'),
        ('project', '0005_remove_tache_agence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tachetime',
            name='jour',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='technicientache',
            unique_together={('technicien', 'tache')},
        ),
        migrations.RemoveField(
            model_name='technicientache',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='technicientache',
            name='ok',
        ),
    ]
