# Generated by Django 4.1.7 on 2023-07-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_tachetime_jour_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TacheTime',
        ),
    ]
