# Generated by Django 4.2.1 on 2023-07-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_delete_tachetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp', models.TextField(verbose_name='rapport')),
                ('techtache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.technicientache')),
            ],
        ),
    ]
