# Generated by Django 4.2.1 on 2023-06-13 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_technicientache_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='tec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.technicientache', verbose_name=''),
            preserve_default=False,
        ),
    ]
