# Generated by Django 4.2.1 on 2023-06-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0006_alter_technicien_photo'),
        ('project', '0008_tache_tec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='tec',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='technicien',
        ),
        migrations.AddField(
            model_name='technicientache',
            name='tache',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.tache'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='technicientache',
            unique_together={('technicien', 'tache', 'nom')},
        ),
        migrations.CreateModel(
            name='TacheTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[], max_length=50, verbose_name='jour')),
                ('technicientache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.technicientache')),
            ],
        ),
        migrations.RemoveField(
            model_name='technicientache',
            name='technicien',
        ),
        migrations.AddField(
            model_name='technicientache',
            name='technicien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ressource.technicien', verbose_name='techniciens'),
            preserve_default=False,
        ),
    ]
