# Generated by Django 4.2.1 on 2023-08-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressource', '0006_technicien_efficacite_technicien_vitesse_execution'),
        ('project', '0009_historicaltechnicientache_historicaltache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheEffectuee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date d'effectuation")),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tache', verbose_name='Tâche effectuée')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressource.technicien', verbose_name='Technicien')),
            ],
        ),
        migrations.CreateModel(
            name='TacheAttribuee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribuee', models.DateTimeField(auto_now_add=True, verbose_name="Date d'attribution")),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tache', verbose_name='Tâche attribuée')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressource.technicien', verbose_name='Technicien')),
            ],
        ),
        migrations.CreateModel(
            name='EnregistrementJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tache')),
            ],
        ),
    ]
