# Generated by Django 4.2.1 on 2023-08-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_tacheeffectuee_tacheattribuee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalRapport',
        ),
    ]
