# Generated by Django 4.2.1 on 2023-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_historicaltechnicientache_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='ok',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HistoricalEtat',
        ),
    ]
