# Generated by Django 4.2.1 on 2023-08-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_technicientache_ok_alter_tacheeffectuee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicientache',
            name='ok',
            field=models.BooleanField(default=False, verbose_name='tache effectuer'),
        ),
    ]
