# Generated by Django 4.2.1 on 2023-06-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('responsable', models.CharField(max_length=100, verbose_name='responsable')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('responsable', models.CharField(max_length=100, verbose_name='responsable')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appelant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='appelant')),
                ('addAt', models.DateField(auto_now_add=True, verbose_name='ajouter le')),
                ('updAt', models.DateField(auto_now=True, verbose_name='mise a jour le')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.agence', verbose_name='agence')),
            ],
        ),
        migrations.AddField(
            model_name='agence',
            name='siege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
