# Generated by Django 4.2.1 on 2023-06-14 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_company",
            new_name="is_helpdesk",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_employee",
            new_name="is_technicien",
        ),
    ]
